export class AppRouterMap {
  static readonly FIND_HOSPITALS = 'FIND_HOSPITALS'
  static readonly LOGIN = 'LOGIN'
  static readonly REG = 'REG'
  static readonly DOCTORS = 'DOCTORS'
  static readonly GOODS_LIST = 'GOODS_LIST'
  static readonly GOODS_DETAIL = 'GOODS_DETAIL'
  static readonly CART = 'CART'
  static readonly ARTICLE_LIST = 'ARTICLE_LIST'
  static readonly ARTICLE_DETAIL = 'ARTICLE_DETAIL'
  static readonly USER_INFO = 'USER_INFO' // 用户信息
}