export { HealthView } from './health'

export { HomeView } from './home'

export { KnowledgeView } from './knowledge'

export { UserView } from './user'

export  { HospitalsView } from './hospitals'
export  { PageNotFoundView } from './page_not_found'
export { LoginView } from './login'
export { RegView } from './reg'
export { DoctorsView } from './doctors'
export { GoodsListView } from './goods_list'
export { GoodsDetailView } from './goods_detail'
export { ArticleListView } from './article_list'
export { ArticleDetailView } from './article_detail'
export { CartView } from './cart'
export { UserInfoView } from './user_info'